<?xml version="1.0" encoding="UTF-8" ?>
<Package name="Load_Libs_Sample" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="libfreetype.6" src="lib/PIL/.dylibs/libfreetype.6.dylib" />
        <File name="libjpeg.9" src="lib/PIL/.dylibs/libjpeg.9.dylib" />
        <File name="liblcms2.2" src="lib/PIL/.dylibs/liblcms2.2.dylib" />
        <File name="liblzma.5" src="lib/PIL/.dylibs/liblzma.5.dylib" />
        <File name="libopenjp2.2.1.0" src="lib/PIL/.dylibs/libopenjp2.2.1.0.dylib" />
        <File name="libpng16.16" src="lib/PIL/.dylibs/libpng16.16.dylib" />
        <File name="libtiff.5" src="lib/PIL/.dylibs/libtiff.5.dylib" />
        <File name="libwebp.6" src="lib/PIL/.dylibs/libwebp.6.dylib" />
        <File name="libwebpdemux.2" src="lib/PIL/.dylibs/libwebpdemux.2.dylib" />
        <File name="libwebpmux.2" src="lib/PIL/.dylibs/libwebpmux.2.dylib" />
        <File name="libz.1.2.8" src="lib/PIL/.dylibs/libz.1.2.8.dylib" />
        <File name="BdfFontFile" src="lib/PIL/BdfFontFile.py" />
        <File name="BdfFontFile" src="lib/PIL/BdfFontFile.pyc" />
        <File name="BmpImagePlugin" src="lib/PIL/BmpImagePlugin.py" />
        <File name="BmpImagePlugin" src="lib/PIL/BmpImagePlugin.pyc" />
        <File name="BufrStubImagePlugin" src="lib/PIL/BufrStubImagePlugin.py" />
        <File name="BufrStubImagePlugin" src="lib/PIL/BufrStubImagePlugin.pyc" />
        <File name="ContainerIO" src="lib/PIL/ContainerIO.py" />
        <File name="ContainerIO" src="lib/PIL/ContainerIO.pyc" />
        <File name="CurImagePlugin" src="lib/PIL/CurImagePlugin.py" />
        <File name="CurImagePlugin" src="lib/PIL/CurImagePlugin.pyc" />
        <File name="DcxImagePlugin" src="lib/PIL/DcxImagePlugin.py" />
        <File name="DcxImagePlugin" src="lib/PIL/DcxImagePlugin.pyc" />
        <File name="DdsImagePlugin" src="lib/PIL/DdsImagePlugin.py" />
        <File name="DdsImagePlugin" src="lib/PIL/DdsImagePlugin.pyc" />
        <File name="EpsImagePlugin" src="lib/PIL/EpsImagePlugin.py" />
        <File name="EpsImagePlugin" src="lib/PIL/EpsImagePlugin.pyc" />
        <File name="ExifTags" src="lib/PIL/ExifTags.py" />
        <File name="ExifTags" src="lib/PIL/ExifTags.pyc" />
        <File name="FitsStubImagePlugin" src="lib/PIL/FitsStubImagePlugin.py" />
        <File name="FitsStubImagePlugin" src="lib/PIL/FitsStubImagePlugin.pyc" />
        <File name="FliImagePlugin" src="lib/PIL/FliImagePlugin.py" />
        <File name="FliImagePlugin" src="lib/PIL/FliImagePlugin.pyc" />
        <File name="FontFile" src="lib/PIL/FontFile.py" />
        <File name="FontFile" src="lib/PIL/FontFile.pyc" />
        <File name="FpxImagePlugin" src="lib/PIL/FpxImagePlugin.py" />
        <File name="FpxImagePlugin" src="lib/PIL/FpxImagePlugin.pyc" />
        <File name="FtexImagePlugin" src="lib/PIL/FtexImagePlugin.py" />
        <File name="FtexImagePlugin" src="lib/PIL/FtexImagePlugin.pyc" />
        <File name="GbrImagePlugin" src="lib/PIL/GbrImagePlugin.py" />
        <File name="GbrImagePlugin" src="lib/PIL/GbrImagePlugin.pyc" />
        <File name="GdImageFile" src="lib/PIL/GdImageFile.py" />
        <File name="GdImageFile" src="lib/PIL/GdImageFile.pyc" />
        <File name="GifImagePlugin" src="lib/PIL/GifImagePlugin.py" />
        <File name="GifImagePlugin" src="lib/PIL/GifImagePlugin.pyc" />
        <File name="GimpGradientFile" src="lib/PIL/GimpGradientFile.py" />
        <File name="GimpGradientFile" src="lib/PIL/GimpGradientFile.pyc" />
        <File name="GimpPaletteFile" src="lib/PIL/GimpPaletteFile.py" />
        <File name="GimpPaletteFile" src="lib/PIL/GimpPaletteFile.pyc" />
        <File name="GribStubImagePlugin" src="lib/PIL/GribStubImagePlugin.py" />
        <File name="GribStubImagePlugin" src="lib/PIL/GribStubImagePlugin.pyc" />
        <File name="Hdf5StubImagePlugin" src="lib/PIL/Hdf5StubImagePlugin.py" />
        <File name="Hdf5StubImagePlugin" src="lib/PIL/Hdf5StubImagePlugin.pyc" />
        <File name="IcnsImagePlugin" src="lib/PIL/IcnsImagePlugin.py" />
        <File name="IcnsImagePlugin" src="lib/PIL/IcnsImagePlugin.pyc" />
        <File name="IcoImagePlugin" src="lib/PIL/IcoImagePlugin.py" />
        <File name="IcoImagePlugin" src="lib/PIL/IcoImagePlugin.pyc" />
        <File name="ImImagePlugin" src="lib/PIL/ImImagePlugin.py" />
        <File name="ImImagePlugin" src="lib/PIL/ImImagePlugin.pyc" />
        <File name="Image" src="lib/PIL/Image.py" />
        <File name="Image" src="lib/PIL/Image.pyc" />
        <File name="ImageChops" src="lib/PIL/ImageChops.py" />
        <File name="ImageChops" src="lib/PIL/ImageChops.pyc" />
        <File name="ImageCms" src="lib/PIL/ImageCms.py" />
        <File name="ImageCms" src="lib/PIL/ImageCms.pyc" />
        <File name="ImageColor" src="lib/PIL/ImageColor.py" />
        <File name="ImageColor" src="lib/PIL/ImageColor.pyc" />
        <File name="ImageDraw" src="lib/PIL/ImageDraw.py" />
        <File name="ImageDraw" src="lib/PIL/ImageDraw.pyc" />
        <File name="ImageDraw2" src="lib/PIL/ImageDraw2.py" />
        <File name="ImageDraw2" src="lib/PIL/ImageDraw2.pyc" />
        <File name="ImageEnhance" src="lib/PIL/ImageEnhance.py" />
        <File name="ImageEnhance" src="lib/PIL/ImageEnhance.pyc" />
        <File name="ImageFile" src="lib/PIL/ImageFile.py" />
        <File name="ImageFile" src="lib/PIL/ImageFile.pyc" />
        <File name="ImageFilter" src="lib/PIL/ImageFilter.py" />
        <File name="ImageFilter" src="lib/PIL/ImageFilter.pyc" />
        <File name="ImageFont" src="lib/PIL/ImageFont.py" />
        <File name="ImageFont" src="lib/PIL/ImageFont.pyc" />
        <File name="ImageGrab" src="lib/PIL/ImageGrab.py" />
        <File name="ImageGrab" src="lib/PIL/ImageGrab.pyc" />
        <File name="ImageMath" src="lib/PIL/ImageMath.py" />
        <File name="ImageMath" src="lib/PIL/ImageMath.pyc" />
        <File name="ImageMode" src="lib/PIL/ImageMode.py" />
        <File name="ImageMode" src="lib/PIL/ImageMode.pyc" />
        <File name="ImageMorph" src="lib/PIL/ImageMorph.py" />
        <File name="ImageMorph" src="lib/PIL/ImageMorph.pyc" />
        <File name="ImageOps" src="lib/PIL/ImageOps.py" />
        <File name="ImageOps" src="lib/PIL/ImageOps.pyc" />
        <File name="ImagePalette" src="lib/PIL/ImagePalette.py" />
        <File name="ImagePalette" src="lib/PIL/ImagePalette.pyc" />
        <File name="ImagePath" src="lib/PIL/ImagePath.py" />
        <File name="ImagePath" src="lib/PIL/ImagePath.pyc" />
        <File name="ImageQt" src="lib/PIL/ImageQt.py" />
        <File name="ImageQt" src="lib/PIL/ImageQt.pyc" />
        <File name="ImageSequence" src="lib/PIL/ImageSequence.py" />
        <File name="ImageSequence" src="lib/PIL/ImageSequence.pyc" />
        <File name="ImageShow" src="lib/PIL/ImageShow.py" />
        <File name="ImageShow" src="lib/PIL/ImageShow.pyc" />
        <File name="ImageStat" src="lib/PIL/ImageStat.py" />
        <File name="ImageStat" src="lib/PIL/ImageStat.pyc" />
        <File name="ImageTk" src="lib/PIL/ImageTk.py" />
        <File name="ImageTk" src="lib/PIL/ImageTk.pyc" />
        <File name="ImageTransform" src="lib/PIL/ImageTransform.py" />
        <File name="ImageTransform" src="lib/PIL/ImageTransform.pyc" />
        <File name="ImageWin" src="lib/PIL/ImageWin.py" />
        <File name="ImageWin" src="lib/PIL/ImageWin.pyc" />
        <File name="ImtImagePlugin" src="lib/PIL/ImtImagePlugin.py" />
        <File name="ImtImagePlugin" src="lib/PIL/ImtImagePlugin.pyc" />
        <File name="IptcImagePlugin" src="lib/PIL/IptcImagePlugin.py" />
        <File name="IptcImagePlugin" src="lib/PIL/IptcImagePlugin.pyc" />
        <File name="Jpeg2KImagePlugin" src="lib/PIL/Jpeg2KImagePlugin.py" />
        <File name="Jpeg2KImagePlugin" src="lib/PIL/Jpeg2KImagePlugin.pyc" />
        <File name="JpegImagePlugin" src="lib/PIL/JpegImagePlugin.py" />
        <File name="JpegImagePlugin" src="lib/PIL/JpegImagePlugin.pyc" />
        <File name="JpegPresets" src="lib/PIL/JpegPresets.py" />
        <File name="JpegPresets" src="lib/PIL/JpegPresets.pyc" />
        <File name="McIdasImagePlugin" src="lib/PIL/McIdasImagePlugin.py" />
        <File name="McIdasImagePlugin" src="lib/PIL/McIdasImagePlugin.pyc" />
        <File name="MicImagePlugin" src="lib/PIL/MicImagePlugin.py" />
        <File name="MicImagePlugin" src="lib/PIL/MicImagePlugin.pyc" />
        <File name="MpegImagePlugin" src="lib/PIL/MpegImagePlugin.py" />
        <File name="MpegImagePlugin" src="lib/PIL/MpegImagePlugin.pyc" />
        <File name="MpoImagePlugin" src="lib/PIL/MpoImagePlugin.py" />
        <File name="MpoImagePlugin" src="lib/PIL/MpoImagePlugin.pyc" />
        <File name="MspImagePlugin" src="lib/PIL/MspImagePlugin.py" />
        <File name="MspImagePlugin" src="lib/PIL/MspImagePlugin.pyc" />
        <File name="OleFileIO-README" src="lib/PIL/OleFileIO-README.md" />
        <File name="OleFileIO" src="lib/PIL/OleFileIO.py" />
        <File name="OleFileIO" src="lib/PIL/OleFileIO.pyc" />
        <File name="PSDraw" src="lib/PIL/PSDraw.py" />
        <File name="PSDraw" src="lib/PIL/PSDraw.pyc" />
        <File name="PaletteFile" src="lib/PIL/PaletteFile.py" />
        <File name="PaletteFile" src="lib/PIL/PaletteFile.pyc" />
        <File name="PalmImagePlugin" src="lib/PIL/PalmImagePlugin.py" />
        <File name="PalmImagePlugin" src="lib/PIL/PalmImagePlugin.pyc" />
        <File name="PcdImagePlugin" src="lib/PIL/PcdImagePlugin.py" />
        <File name="PcdImagePlugin" src="lib/PIL/PcdImagePlugin.pyc" />
        <File name="PcfFontFile" src="lib/PIL/PcfFontFile.py" />
        <File name="PcfFontFile" src="lib/PIL/PcfFontFile.pyc" />
        <File name="PcxImagePlugin" src="lib/PIL/PcxImagePlugin.py" />
        <File name="PcxImagePlugin" src="lib/PIL/PcxImagePlugin.pyc" />
        <File name="PdfImagePlugin" src="lib/PIL/PdfImagePlugin.py" />
        <File name="PdfImagePlugin" src="lib/PIL/PdfImagePlugin.pyc" />
        <File name="PixarImagePlugin" src="lib/PIL/PixarImagePlugin.py" />
        <File name="PixarImagePlugin" src="lib/PIL/PixarImagePlugin.pyc" />
        <File name="PngImagePlugin" src="lib/PIL/PngImagePlugin.py" />
        <File name="PngImagePlugin" src="lib/PIL/PngImagePlugin.pyc" />
        <File name="PpmImagePlugin" src="lib/PIL/PpmImagePlugin.py" />
        <File name="PpmImagePlugin" src="lib/PIL/PpmImagePlugin.pyc" />
        <File name="PsdImagePlugin" src="lib/PIL/PsdImagePlugin.py" />
        <File name="PsdImagePlugin" src="lib/PIL/PsdImagePlugin.pyc" />
        <File name="PyAccess" src="lib/PIL/PyAccess.py" />
        <File name="PyAccess" src="lib/PIL/PyAccess.pyc" />
        <File name="SgiImagePlugin" src="lib/PIL/SgiImagePlugin.py" />
        <File name="SgiImagePlugin" src="lib/PIL/SgiImagePlugin.pyc" />
        <File name="SpiderImagePlugin" src="lib/PIL/SpiderImagePlugin.py" />
        <File name="SpiderImagePlugin" src="lib/PIL/SpiderImagePlugin.pyc" />
        <File name="SunImagePlugin" src="lib/PIL/SunImagePlugin.py" />
        <File name="SunImagePlugin" src="lib/PIL/SunImagePlugin.pyc" />
        <File name="TarIO" src="lib/PIL/TarIO.py" />
        <File name="TarIO" src="lib/PIL/TarIO.pyc" />
        <File name="TgaImagePlugin" src="lib/PIL/TgaImagePlugin.py" />
        <File name="TgaImagePlugin" src="lib/PIL/TgaImagePlugin.pyc" />
        <File name="TiffImagePlugin" src="lib/PIL/TiffImagePlugin.py" />
        <File name="TiffImagePlugin" src="lib/PIL/TiffImagePlugin.pyc" />
        <File name="TiffTags" src="lib/PIL/TiffTags.py" />
        <File name="TiffTags" src="lib/PIL/TiffTags.pyc" />
        <File name="WalImageFile" src="lib/PIL/WalImageFile.py" />
        <File name="WalImageFile" src="lib/PIL/WalImageFile.pyc" />
        <File name="WebPImagePlugin" src="lib/PIL/WebPImagePlugin.py" />
        <File name="WebPImagePlugin" src="lib/PIL/WebPImagePlugin.pyc" />
        <File name="WmfImagePlugin" src="lib/PIL/WmfImagePlugin.py" />
        <File name="WmfImagePlugin" src="lib/PIL/WmfImagePlugin.pyc" />
        <File name="XVThumbImagePlugin" src="lib/PIL/XVThumbImagePlugin.py" />
        <File name="XVThumbImagePlugin" src="lib/PIL/XVThumbImagePlugin.pyc" />
        <File name="XbmImagePlugin" src="lib/PIL/XbmImagePlugin.py" />
        <File name="XbmImagePlugin" src="lib/PIL/XbmImagePlugin.pyc" />
        <File name="XpmImagePlugin" src="lib/PIL/XpmImagePlugin.py" />
        <File name="XpmImagePlugin" src="lib/PIL/XpmImagePlugin.pyc" />
        <File name="__init__" src="lib/PIL/__init__.py" />
        <File name="__init__" src="lib/PIL/__init__.pyc" />
        <File name="_binary" src="lib/PIL/_binary.py" />
        <File name="_binary" src="lib/PIL/_binary.pyc" />
        <File name="_imaging" src="lib/PIL/_imaging.so" />
        <File name="_imagingcms" src="lib/PIL/_imagingcms.so" />
        <File name="_imagingft" src="lib/PIL/_imagingft.so" />
        <File name="_imagingmath" src="lib/PIL/_imagingmath.so" />
        <File name="_imagingmorph" src="lib/PIL/_imagingmorph.so" />
        <File name="_imagingtk" src="lib/PIL/_imagingtk.so" />
        <File name="_tkinter_finder" src="lib/PIL/_tkinter_finder.py" />
        <File name="_tkinter_finder" src="lib/PIL/_tkinter_finder.pyc" />
        <File name="_util" src="lib/PIL/_util.py" />
        <File name="_util" src="lib/PIL/_util.pyc" />
        <File name="_webp" src="lib/PIL/_webp.so" />
        <File name="features" src="lib/PIL/features.py" />
        <File name="features" src="lib/PIL/features.pyc" />
    </Resources>
    <Topics />
    <IgnoredPaths>
        <Path src=".metadata" />
    </IgnoredPaths>
</Package>
